language: rust
rust:
- stable
- beta
- nightly


before_install:
- nvm install node

install:
- cargo build --verbose --examples --tests --lib
- cd node-tests && npm install

script:
- cargo test --verbose
- cd $TRAVIS_BUILD_DIR/node-tests && ./connect_test.sh

jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
